baseURL = "https://tdgne.dev/"
title = "tdgneのサイト"
theme = "hugo-theme-cleanwhite"
languageCode = "ja-jp"
hasCJKLanguage = true
googleAnalytics = "UA-54765878-8"

[outputs]
home = ["HTML", "RSS"]

[params]
header_image = "images/header.jpg"
about_me = true
sidebar_about_description = "進化生態学とRustが好きな修士（理学）。2019年春からソフトウェアエンジニアになります。"

[params.social]
twitter = "https://twitter.com/feliscatusfelis"
github = "https://github.com/tdgne"

[blackfriday]
hrefTargetBlank = true
