baseURL = "https://tdgne.dev/"
title = "tdgneのサイト"
theme = "hugo-theme-cleanwhite"
languageCode = "ja-jp"
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
header_image = "images/header.jpg"

[blackfriday]
hrefTargetBlank = true
